baseURL = 'https://sumbawanga.org.uk/'
languageCode = 'en-gb'
title = 'Sumbawanga Development Action'
theme = 'ananke'
[params]
  custom_css = [ "/custom.css" ]

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 3